FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# 実行ステージ
FROM nginx:stable-alpine
WORKDIR /dist
COPY --from=builder /app/dist .
CMD ["sh", "-c", "cp -rp /dist/* /output/"]