# backend/Dockerfile.backend
FROM golang:1.26-alpine

RUN apk add --no-cache gcc musl-dev

WORKDIR /app

ENV CGO_ENABLED=1

RUN go install github.com/air-verse/air@latest

COPY go.mod* go.sum* ./
RUN if [ -f go.mod ]; then go mod download; fi